//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int order_line_id { get; set; }
        public int order_id { get; set; }
        public int order_line_product_id { get; set; }
        public decimal order_line_quantity { get; set; }
        public int order_line_unit_id { get; set; }
        public decimal order_line_unit_price { get; set; }
        public decimal order_line_total { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
