//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int price_id { get; set; }
        public System.DateTime price_date { get; set; }
        public string price_type { get; set; }
        public int price_item_id { get; set; }
        public decimal price_value { get; set; }
        public string price_currency { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
