//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaterial
    {
        public int production_material_id { get; set; }
        public int production_id { get; set; }
        public int production_mat_material_id { get; set; }
        public decimal production_mat_quantity { get; set; }
        public int production_mat_unit_id { get; set; }
        public decimal production_mat_unit_price { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Production Production { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
