//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionProduct
    {
        public int production_product_id { get; set; }
        public int production_id { get; set; }
        public int production_prod_product_id { get; set; }
        public decimal production_prod_quantity { get; set; }
        public int production_prod_unit_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Production Production { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
