//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationMaterial
    {
        public int spec_material_id { get; set; }
        public int spec_id { get; set; }
        public int spec_mat_material_id { get; set; }
        public decimal spec_mat_quantity { get; set; }
        public int spec_mat_unit_id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Specification Specification { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
