//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification()
        {
            this.SpecificationMaterial = new HashSet<SpecificationMaterial>();
        }
    
        public int spec_id { get; set; }
        public string spec_name { get; set; }
        public int spec_product_id { get; set; }
        public string spec_manufacturer_id { get; set; }
        public System.DateTime spec_created_date { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationMaterial> SpecificationMaterial { get; set; }
    }
}
