//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.CustomerOrder = new HashSet<CustomerOrder>();
        }
    
        public int user_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public Nullable<bool> is_blocked { get; set; }
        public Nullable<int> failed_attempts { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string customer_id { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrder { get; set; }
        public virtual role role { get; set; }
    }
}
