//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Xlebobylochnoe.ApplicationDateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBXlebobylochnoeEntities : DbContext
    {
        public DBXlebobylochnoeEntities()
            : base("name=DBXlebobylochnoeEntities")
        {
        }

        private static DBXlebobylochnoeEntities _context;

        public static DBXlebobylochnoeEntities GetContext()
        {
            if (_context == null)
                _context = new DBXlebobylochnoeEntities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrder { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialCategory> MaterialCategory { get; set; }
        public virtual DbSet<OrderLine> OrderLine { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<ProductionMaterial> ProductionMaterial { get; set; }
        public virtual DbSet<ProductionProduct> ProductionProduct { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<SpecificationMaterial> SpecificationMaterial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
